In [24]:
import joblib
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
from statistics import mode

In [2]:
logistic_regression = joblib.load('logistic_regression_model.joblib')

In [3]:
logistic_regression_scaled = joblib.load('logistic_regression_scaled_model.joblib')

In [17]:
svm = joblib.load('support_vector_machine_scaled_model.joblib')

In [11]:
scaler = joblib.load('scaler.joblib')

In [8]:
X_test = pd.read_csv('test/test_9_testing.csv')

In [12]:
X_test_scaled = scaler.transform(X_test)

In [13]:
logreg = logistic_regression.predict(X_test)
logreg

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 4., 4., 3., 3., 3., 2., 2., 2., 2., 2., 2., 2.])

In [15]:
logreg1 = logistic_regression_scaled.predict(X_test_scaled)
logreg1

array([2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 5., 4., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 4., 4., 4., 4., 4., 4., 3., 3., 3., 2., 2., 3., 3., 3., 3.])

In [18]:
svm_predict = svm.predict(X_test_scaled)
svm_predict

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 4., 4., 4., 4., 4., 4., 3., 3., 3., 2., 2., 2., 2., 2., 2., 2.])

In [22]:
all_predict= np.array([logreg,logreg1,svm_predict])

In [28]:
combined_predict = np.apply_along_axis(mode, axis=0, arr=all_predict)
len(combined_predict)

119

In [26]:
predict_9_new = pd.read_csv('test/predict_9.csv')

In [29]:
predict_9_new['new_combined']=combined_predict

In [30]:
predict_9_new.to_csv('test/predict_new_9.csv',index=False)